### ISSUE TITLE
可以一起交流

### ISSUE THREAD

**Issue by ZGA101421** [TokikiriNanaya/luoShiXiaoZhu#1]
hhhh

**Comment by TokikiriNanaya** [comment]
啊这...

**Comment by ZGA101421** [comment]
可以试试抓小程序的包，我做了这个方面的。快一年了

**Comment by sunshine2443** [comment]
这怎么用啊

**Comment by ZGA101421** [comment]
> 



> 这怎么用啊

配置文件写你的账号密码，把这个文件部署到云函数定时运行就好了

**Comment by sunshine2443** [comment]
这是我配置的账号密码，你看一下对不对，我算小白，不太懂这些，这个文件要怎么部署给云函数，麻烦你指导一下，嘿嘿。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TokikiriNanaya/luoShiXiaoZhu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月30日(星期天) 上午6:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TokikiriNanaya/luoShiXiaoZhu] 可以一起交流 (#1)





    
这怎么用啊
  
配置文件写你的账号密码，把这个文件部署到云函数定时运行就好了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sunshine2443** [comment]
> 
谢谢你的回复，麻烦再赐教一下，嘻嘻

**Comment by sunshine2443** [comment]
请问腾讯云的云函数计算可以吗，但我这样部署提示说未找到执行入口文件，请问您这样要怎么弄啊？麻烦了。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TokikiriNanaya/luoShiXiaoZhu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月30日(星期天) 上午6:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TokikiriNanaya/luoShiXiaoZhu] 可以一起交流 (#1)





    
这怎么用啊
  
配置文件写你的账号密码，把这个文件部署到云函数定时运行就好了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sunshine2443** [comment]
最后问一下，代码里面写入的那几个网址怎么是空的网页？

**Comment by TokikiriNanaya** [comment]
啊不好意思最近没怎么看 刚刚更新了一下 你看一下readme把 需要一定的玩机经验和编程基础

**Comment by ZGA101421** [comment]
> 

jwt可以通过重新登录向login发出get请求抓取返回值获取的，具体要抓包看一下，或者看一下我的代码，上报信息的话也可以使用历史数据，这样

**Comment by TokikiriNanaya** [comment]
> > 
> 
> jwt可以通过重新登录向login发出get请求抓取返回值获取的，具体要抓包看一下，或者看一下我的代码，上报信息的话也可以使用历史数据，这样

我更新了一下 抓包只需要在晨报页面提交的时候抓一下就行了 里面有jwt和位置信息

**Comment by ZGA101421** [comment]
刚刚把仓库public了，可以看一下

**Comment by ZGA101421** [comment]
删库跑路了兄弟
